language: node_js
node_js:
  "10"
install:
  - yarn install
script:
- yarn run build
- (cd normalize-js && yarn run test)
- (cd stopify-continuations-compiler && yarn run test)
- (cd stopify && yarn run test)
cache:
  directories:
  - node_modules
notifications:
  email:false
addons:
  chrome: stable
  firefox: latest